### ISSUE TITLE
Could you compile it with openjdk 17.0.12 2024-07-16 

### ISSUE THREAD

**Issue by astream2018** [karimalaa-bbi/kafka-connect-xml-transform#1]
I try to comiple the orginal github repo, but its was missing lots of dependencies.

org.apache.kafka.connect.errors.ConnectException: java.lang.UnsupportedClassVersionError: com/github/jcustenborder/kafka/connect/xml/Connectable has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by karimalaa-bbi** [comment]
The file **jcustenborder-kafka-connect-transform-xml-0.3.0-SNAPSHOT.zip** was compiled using OpenJDK 17.0.12. I was able to compile it after updating the dependency versions in the pom.xml file.

**Comment by astream2018** [comment]
0.1.0 worked for me thanks
